# Don't forget to export following env variables:
# X_WPPR_USERNAME
# X_WPPR_PASSWORD
token: "xxx"
fileDir: "/tmp/wpprfiles/"
allowedIDs:
  - 247671430
  - 418367041
logFile: "/tmp/wpprlog.log"
certFilePath: "/path/"
certKeyPath: "/path"
Username: "username"
Password: "Password"